dependencies:
  # - <organization/repo>@<version>
  - shambadynamic/shamba-smartcontractkit@1.3.0
  - smartcontractkit/chainlink@1.4.1
  - OpenZeppelin/openzeppelin-contracts@4.6.0
compiler:
  solc:
    remappings:
      - '@shamba=shambadynamic/shamba-smartcontractkit@1.3.0'
      - '@chainlink=smartcontractkit/chainlink@1.4.1'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.6.0'
dotenv: .env
wallets:
  from_key: ${PRIVATE_KEY}